version: "3.8"
   
services:
  web:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    depends_on: 
      - db
  db:
    image: mongo:latest
    environment: 
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports: 
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    
volumes:
  mongodb_data_container: