# DEVELOPMENT DOCKER COMPOSE
version: "3.8"
   
services:
  web:
    build:
      context: .
      dockerfile: ./development.Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    depends_on: 
      - db
  db:
    image: mongo:latest
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports: 
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    
volumes:
  mongodb_data_container: